export const peiLocations = [
  // CHARLOTTETOWN - DOWNTOWN
  "1 Queen St, Charlottetown, PE",
  "5 Queen St, Charlottetown, PE",
  "10 Queen St, Charlottetown, PE",
  "15 Queen St, Charlottetown, PE",
  "20 Queen St, Charlottetown, PE",
  "25 Queen St, Charlottetown, PE",
  "30 Queen St, Charlottetown, PE",
  "35 Queen St, Charlottetown, PE",
  "40 Queen St, Charlottetown, PE",
  "45 Queen St, Charlottetown, PE",
  "50 Queen St, Charlottetown, PE",
  "55 Queen St, Charlottetown, PE",
  "60 Queen St, Charlottetown, PE",
  "65 Queen St, Charlottetown, PE",
  "70 Queen St, Charlottetown, PE",
  "75 Queen St, Charlottetown, PE",
  "80 Queen St, Charlottetown, PE",
  "85 Queen St, Charlottetown, PE",
  "90 Queen St, Charlottetown, PE",
  "95 Queen St, Charlottetown, PE",
  "100 Queen St, Charlottetown, PE",
  "105 Queen St, Charlottetown, PE",
  "110 Queen St, Charlottetown, PE",
  "115 Queen St, Charlottetown, PE",
  "120 Queen St, Charlottetown, PE",
  "125 Queen St, Charlottetown, PE",
  "130 Queen St, Charlottetown, PE",
  "135 Queen St, Charlottetown, PE",
  "140 Queen St, Charlottetown, PE",
  "145 Queen St, Charlottetown, PE",
  "150 Queen St, Charlottetown, PE",

  "1 Great George St, Charlottetown, PE",
  "5 Great George St, Charlottetown, PE",
  "10 Great George St, Charlottetown, PE",
  "15 Great George St, Charlottetown, PE",
  "20 Great George St, Charlottetown, PE",
  "25 Great George St, Charlottetown, PE",
  "30 Great George St, Charlottetown, PE",
  "35 Great George St, Charlottetown, PE",
  "40 Great George St, Charlottetown, PE",
  "45 Great George St, Charlottetown, PE",
  "50 Great George St, Charlottetown, PE",
  "55 Great George St, Charlottetown, PE",
  "58 Great George St, Charlottetown, PE",
  "60 Great George St, Charlottetown, PE",
  "65 Great George St, Charlottetown, PE",
  "70 Great George St, Charlottetown, PE",
  "75 Great George St, Charlottetown, PE",
  "80 Great George St, Charlottetown, PE",
  "85 Great George St, Charlottetown, PE",
  "90 Great George St, Charlottetown, PE",
  "95 Great George St, Charlottetown, PE",
  "100 Great George St, Charlottetown, PE",

  "1 Kent St, Charlottetown, PE",
  "5 Kent St, Charlottetown, PE",
  "10 Kent St, Charlottetown, PE",
  "15 Kent St, Charlottetown, PE",
  "20 Kent St, Charlottetown, PE",
  "25 Kent St, Charlottetown, PE",
  "30 Kent St, Charlottetown, PE",
  "35 Kent St, Charlottetown, PE",
  "40 Kent St, Charlottetown, PE",
  "45 Kent St, Charlottetown, PE",
  "50 Kent St, Charlottetown, PE",
  "55 Kent St, Charlottetown, PE",
  "60 Kent St, Charlottetown, PE",
  "65 Kent St, Charlottetown, PE",
  "70 Kent St, Charlottetown, PE",
  "75 Kent St, Charlottetown, PE",
  "80 Kent St, Charlottetown, PE",
  "85 Kent St, Charlottetown, PE",
  "90 Kent St, Charlottetown, PE",
  "95 Kent St, Charlottetown, PE",
  "100 Kent St, Charlottetown, PE",
  "105 Kent St, Charlottetown, PE",
  "110 Kent St, Charlottetown, PE",
  "115 Kent St, Charlottetown, PE",
  "120 Kent St, Charlottetown, PE",
  "125 Kent St, Charlottetown, PE",
  "130 Kent St, Charlottetown, PE",
  "135 Kent St, Charlottetown, PE",
  "140 Kent St, Charlottetown, PE",
  "145 Kent St, Charlottetown, PE",
  "150 Kent St, Charlottetown, PE",
  "155 Kent St, Charlottetown, PE",
  "160 Kent St, Charlottetown, PE",
  "165 Kent St, Charlottetown, PE",
  "170 Kent St, Charlottetown, PE",
  "175 Kent St, Charlottetown, PE",
  "180 Kent St, Charlottetown, PE",
  "185 Kent St, Charlottetown, PE",
  "190 Kent St, Charlottetown, PE",
  "195 Kent St, Charlottetown, PE",
  "200 Kent St, Charlottetown, PE",

  "1 Prince St, Charlottetown, PE",
  "5 Prince St, Charlottetown, PE",
  "6 Prince St, Charlottetown, PE",
  "10 Prince St, Charlottetown, PE",
  "15 Prince St, Charlottetown, PE",
  "20 Prince St, Charlottetown, PE",
  "25 Prince St, Charlottetown, PE",
  "30 Prince St, Charlottetown, PE",
  "35 Prince St, Charlottetown, PE",
  "40 Prince St, Charlottetown, PE",
  "45 Prince St, Charlottetown, PE",
  "50 Prince St, Charlottetown, PE",
  "55 Prince St, Charlottetown, PE",
  "60 Prince St, Charlottetown, PE",
  "65 Prince St, Charlottetown, PE",
  "70 Prince St, Charlottetown, PE",
  "75 Prince St, Charlottetown, PE",
  "80 Prince St, Charlottetown, PE",
  "85 Prince St, Charlottetown, PE",
  "90 Prince St, Charlottetown, PE",
  "95 Prince St, Charlottetown, PE",
  "100 Prince St, Charlottetown, PE",

  "1 Water St, Charlottetown, PE",
  "5 Water St, Charlottetown, PE",
  "10 Water St, Charlottetown, PE",
  "15 Water St, Charlottetown, PE",
  "20 Water St, Charlottetown, PE",
  "25 Water St, Charlottetown, PE",
  "30 Water St, Charlottetown, PE",
  "35 Water St, Charlottetown, PE",
  "38 Water St, Charlottetown, PE",
  "40 Water St, Charlottetown, PE",
  "45 Water St, Charlottetown, PE",
  "50 Water St, Charlottetown, PE",
  "55 Water St, Charlottetown, PE",
  "60 Water St, Charlottetown, PE",
  "65 Water St, Charlottetown, PE",
  "70 Water St, Charlottetown, PE",
  "75 Water St, Charlottetown, PE",
  "80 Water St, Charlottetown, PE",
  "85 Water St, Charlottetown, PE",
  "90 Water St, Charlottetown, PE",
  "95 Water St, Charlottetown, PE",
  "100 Water St, Charlottetown, PE",
  "105 Water St, Charlottetown, PE",
  "110 Water St, Charlottetown, PE",
  "115 Water St, Charlottetown, PE",
  "120 Water St, Charlottetown, PE",
  "125 Water St, Charlottetown, PE",
  "130 Water St, Charlottetown, PE",
  "135 Water St, Charlottetown, PE",
  "140 Water St, Charlottetown, PE",
  "141 Water St, Charlottetown, PE",
  "145 Water St, Charlottetown, PE",
  "150 Water St, Charlottetown, PE",
  "155 Water St, Charlottetown, PE",
  "160 Water St, Charlottetown, PE",
  "165 Water St, Charlottetown, PE",
  "170 Water St, Charlottetown, PE",
  "175 Water St, Charlottetown, PE",
  "180 Water St, Charlottetown, PE",
  "185 Water St, Charlottetown, PE",
  "190 Water St, Charlottetown, PE",
  "195 Water St, Charlottetown, PE",
  "200 Water St, Charlottetown, PE",

  "1 Grafton St, Charlottetown, PE",
  "5 Grafton St, Charlottetown, PE",
  "10 Grafton St, Charlottetown, PE",
  "15 Grafton St, Charlottetown, PE",
  "20 Grafton St, Charlottetown, PE",
  "25 Grafton St, Charlottetown, PE",
  "30 Grafton St, Charlottetown, PE",
  "35 Grafton St, Charlottetown, PE",
  "40 Grafton St, Charlottetown, PE",
  "45 Grafton St, Charlottetown, PE",
  "50 Grafton St, Charlottetown, PE",
  "55 Grafton St, Charlottetown, PE",
  "60 Grafton St, Charlottetown, PE",
  "65 Grafton St, Charlottetown, PE",
  "70 Grafton St, Charlottetown, PE",
  "75 Grafton St, Charlottetown, PE",
  "80 Grafton St, Charlottetown, PE",
  "85 Grafton St, Charlottetown, PE",
  "90 Grafton St, Charlottetown, PE",
  "95 Grafton St, Charlottetown, PE",
  "100 Grafton St, Charlottetown, PE",
  "105 Grafton St, Charlottetown, PE",
  "110 Grafton St, Charlottetown, PE",
  "115 Grafton St, Charlottetown, PE",
  "120 Grafton St, Charlottetown, PE",
  "123 Grafton St, Charlottetown, PE",
  "125 Grafton St, Charlottetown, PE",
  "130 Grafton St, Charlottetown, PE",
  "135 Grafton St, Charlottetown, PE",
  "140 Grafton St, Charlottetown, PE",
  "145 Grafton St, Charlottetown, PE",
  "150 Grafton St, Charlottetown, PE",

  "1 Richmond St, Charlottetown, PE",
  "5 Richmond St, Charlottetown, PE",
  "10 Richmond St, Charlottetown, PE",
  "15 Richmond St, Charlottetown, PE",
  "20 Richmond St, Charlottetown, PE",
  "25 Richmond St, Charlottetown, PE",
  "30 Richmond St, Charlottetown, PE",
  "35 Richmond St, Charlottetown, PE",
  "40 Richmond St, Charlottetown, PE",
  "45 Richmond St, Charlottetown, PE",
  "50 Richmond St, Charlottetown, PE",
  "55 Richmond St, Charlottetown, PE",
  "60 Richmond St, Charlottetown, PE",
  "65 Richmond St, Charlottetown, PE",
  "70 Richmond St, Charlottetown, PE",
  "75 Richmond St, Charlottetown, PE",
  "80 Richmond St, Charlottetown, PE",
  "85 Richmond St, Charlottetown, PE",
  "90 Richmond St, Charlottetown, PE",
  "95 Richmond St, Charlottetown, PE",
  "100 Richmond St, Charlottetown, PE",
  "105 Richmond St, Charlottetown, PE",
  "110 Richmond St, Charlottetown, PE",
  "115 Richmond St, Charlottetown, PE",
  "120 Richmond St, Charlottetown, PE",
  "125 Richmond St, Charlottetown, PE",
  "126 Richmond St, Charlottetown, PE",
  "128 Richmond St, Charlottetown, PE",
  "130 Richmond St, Charlottetown, PE",
  "132 Richmond St, Charlottetown, PE",
  "135 Richmond St, Charlottetown, PE",
  "136 Richmond St, Charlottetown, PE",
  "140 Richmond St, Charlottetown, PE",
  "145 Richmond St, Charlottetown, PE",
  "150 Richmond St, Charlottetown, PE",
  "155 Richmond St, Charlottetown, PE",
  "160 Richmond St, Charlottetown, PE",
  "165 Richmond St, Charlottetown, PE",
  "170 Richmond St, Charlottetown, PE",
  "175 Richmond St, Charlottetown, PE",
  "180 Richmond St, Charlottetown, PE",
  "185 Richmond St, Charlottetown, PE",
  "190 Richmond St, Charlottetown, PE",
  "195 Richmond St, Charlottetown, PE",
  "200 Richmond St, Charlottetown, PE",

  // CHARLOTTETOWN - UNIVERSITY AREA
  "1 University Ave, Charlottetown, PE",
  "10 University Ave, Charlottetown, PE",
  "25 University Ave, Charlottetown, PE",
  "50 University Ave, Charlottetown, PE",
  "75 University Ave, Charlottetown, PE",
  "77 University Ave, Charlottetown, PE",
  "81 University Ave, Charlottetown, PE",
  "84 University Ave, Charlottetown, PE",
  "100 University Ave, Charlottetown, PE",
  "125 University Ave, Charlottetown, PE",
  "150 University Ave, Charlottetown, PE",
  "175 University Ave, Charlottetown, PE",
  "199 University Ave, Charlottetown, PE",
  "200 University Ave, Charlottetown, PE",
  "225 University Ave, Charlottetown, PE",
  "250 University Ave, Charlottetown, PE",
  "275 University Ave, Charlottetown, PE",
  "300 University Ave, Charlottetown, PE",
  "325 University Ave, Charlottetown, PE",
  "350 University Ave, Charlottetown, PE",
  "375 University Ave, Charlottetown, PE",
  "388 University Ave, Charlottetown, PE",
  "400 University Ave, Charlottetown, PE",
  "401 University Ave, Charlottetown, PE",
  "425 University Ave, Charlottetown, PE",
  "450 University Ave, Charlottetown, PE",
  "455 University Ave, Charlottetown, PE",
  "465 University Ave, Charlottetown, PE",
  "475 University Ave, Charlottetown, PE",
  "500 University Ave, Charlottetown, PE",
  "503 University Ave, Charlottetown, PE",
  "525 University Ave, Charlottetown, PE",
  "550 University Ave, Charlottetown, PE",
  "575 University Ave, Charlottetown, PE",
  "600 University Ave, Charlottetown, PE",
  "625 University Ave, Charlottetown, PE",
  "650 University Ave, Charlottetown, PE",
  "670 University Ave, Charlottetown, PE",
  "675 University Ave, Charlottetown, PE",
  "700 University Ave, Charlottetown, PE",

  // CHARLOTTETOWN - BELVEDERE AREA
  "1 Belvedere Ave, Charlottetown, PE",
  "10 Belvedere Ave, Charlottetown, PE",
  "25 Belvedere Ave, Charlottetown, PE",
  "50 Belvedere Ave, Charlottetown, PE",
  "75 Belvedere Ave, Charlottetown, PE",
  "100 Belvedere Ave, Charlottetown, PE",
  "125 Belvedere Ave, Charlottetown, PE",
  "150 Belvedere Ave, Charlottetown, PE",
  "175 Belvedere Ave, Charlottetown, PE",
  "200 Belvedere Ave, Charlottetown, PE",

  // CHARLOTTETOWN - NORTH RIVER ROAD
  "1 North River Rd, Charlottetown, PE",
  "25 North River Rd, Charlottetown, PE",
  "50 North River Rd, Charlottetown, PE",
  "75 North River Rd, Charlottetown, PE",
  "100 North River Rd, Charlottetown, PE",
  "125 North River Rd, Charlottetown, PE",
  "150 North River Rd, Charlottetown, PE",
  "175 North River Rd, Charlottetown, PE",
  "200 North River Rd, Charlottetown, PE",
  "225 North River Rd, Charlottetown, PE",
  "250 North River Rd, Charlottetown, PE",
  "275 North River Rd, Charlottetown, PE",
  "300 North River Rd, Charlottetown, PE",
  "315 North River Rd, Charlottetown, PE",
  "325 North River Rd, Charlottetown, PE",
  "350 North River Rd, Charlottetown, PE",
  "375 North River Rd, Charlottetown, PE",
  "400 North River Rd, Charlottetown, PE",
  "425 North River Rd, Charlottetown, PE",
  "450 North River Rd, Charlottetown, PE",
  "475 North River Rd, Charlottetown, PE",
  "500 North River Rd, Charlottetown, PE",

  // CHARLOTTETOWN - ST. PETERS ROAD
  "1 St. Peters Rd, Charlottetown, PE",
  "25 St. Peters Rd, Charlottetown, PE",
  "33 St. Peters Rd, Charlottetown, PE",
  "50 St. Peters Rd, Charlottetown, PE",
  "75 St. Peters Rd, Charlottetown, PE",
  "100 St. Peters Rd, Charlottetown, PE",
  "125 St. Peters Rd, Charlottetown, PE",
  "150 St. Peters Rd, Charlottetown, PE",
  "175 St. Peters Rd, Charlottetown, PE",
  "200 St. Peters Rd, Charlottetown, PE",
  "225 St. Peters Rd, Charlottetown, PE",
  "250 St. Peters Rd, Charlottetown, PE",
  "275 St. Peters Rd, Charlottetown, PE",
  "300 St. Peters Rd, Charlottetown, PE",
  "325 St. Peters Rd, Charlottetown, PE",
  "350 St. Peters Rd, Charlottetown, PE",
  "375 St. Peters Rd, Charlottetown, PE",
  "400 St. Peters Rd, Charlottetown, PE",
  "425 St. Peters Rd, Charlottetown, PE",
  "450 St. Peters Rd, Charlottetown, PE",
  "475 St. Peters Rd, Charlottetown, PE",
  "500 St. Peters Rd, Charlottetown, PE",

  // CHARLOTTETOWN - MOUNT EDWARD ROAD
  "1 Mount Edward Rd, Charlottetown, PE",
  "25 Mount Edward Rd, Charlottetown, PE",
  "50 Mount Edward Rd, Charlottetown, PE",
  "75 Mount Edward Rd, Charlottetown, PE",
  "100 Mount Edward Rd, Charlottetown, PE",
  "125 Mount Edward Rd, Charlottetown, PE",
  "150 Mount Edward Rd, Charlottetown, PE",
  "175 Mount Edward Rd, Charlottetown, PE",
  "200 Mount Edward Rd, Charlottetown, PE",
  "225 Mount Edward Rd, Charlottetown, PE",
  "250 Mount Edward Rd, Charlottetown, PE",
  "275 Mount Edward Rd, Charlottetown, PE",
  "300 Mount Edward Rd, Charlottetown, PE",

  // CHARLOTTETOWN - KENSINGTON ROAD
  "1 Kensington Rd, Charlottetown, PE",
  "25 Kensington Rd, Charlottetown, PE",
  "50 Kensington Rd, Charlottetown, PE",
  "75 Kensington Rd, Charlottetown, PE",
  "96 Kensington Rd, Charlottetown, PE",
  "100 Kensington Rd, Charlottetown, PE",
  "125 Kensington Rd, Charlottetown, PE",
  "150 Kensington Rd, Charlottetown, PE",
  "175 Kensington Rd, Charlottetown, PE",
  "200 Kensington Rd, Charlottetown, PE",

  // CHARLOTTETOWN - MALPEQUE ROAD
  "1 Malpeque Rd, Charlottetown, PE",
  "25 Malpeque Rd, Charlottetown, PE",
  "50 Malpeque Rd, Charlottetown, PE",
  "75 Malpeque Rd, Charlottetown, PE",
  "100 Malpeque Rd, Charlottetown, PE",
  "125 Malpeque Rd, Charlottetown, PE",
  "150 Malpeque Rd, Charlottetown, PE",
  "175 Malpeque Rd, Charlottetown, PE",
  "200 Malpeque Rd, Charlottetown, PE",
  "225 Malpeque Rd, Charlottetown, PE",
  "250 Malpeque Rd, Charlottetown, PE",
  "275 Malpeque Rd, Charlottetown, PE",
  "300 Malpeque Rd, Charlottetown, PE",

  // CHARLOTTETOWN - ALLEN STREET
  "1 Allen St, Charlottetown, PE",
  "10 Allen St, Charlottetown, PE",
  "25 Allen St, Charlottetown, PE",
  "41 Allen St, Charlottetown, PE",
  "50 Allen St, Charlottetown, PE",
  "75 Allen St, Charlottetown, PE",
  "100 Allen St, Charlottetown, PE",

  // CHARLOTTETOWN - EUSTON STREET
  "1 Euston St, Charlottetown, PE",
  "10 Euston St, Charlottetown, PE",
  "25 Euston St, Charlottetown, PE",
  "50 Euston St, Charlottetown, PE",
  "75 Euston St, Charlottetown, PE",
  "100 Euston St, Charlottetown, PE",
  "125 Euston St, Charlottetown, PE",
  "150 Euston St, Charlottetown, PE",

  // CHARLOTTETOWN - POWNAL STREET
  "1 Pownal St, Charlottetown, PE",
  "10 Pownal St, Charlottetown, PE",
  "25 Pownal St, Charlottetown, PE",
  "50 Pownal St, Charlottetown, PE",
  "75 Pownal St, Charlottetown, PE",
  "100 Pownal St, Charlottetown, PE",

  // CHARLOTTETOWN - SYDNEY STREET
  "1 Sydney St, Charlottetown, PE",
  "10 Sydney St, Charlottetown, PE",
  "25 Sydney St, Charlottetown, PE",
  "50 Sydney St, Charlottetown, PE",
  "75 Sydney St, Charlottetown, PE",
  "100 Sydney St, Charlottetown, PE",
  "125 Sydney St, Charlottetown, PE",
  "126 Sydney St, Charlottetown, PE",
  "130 Sydney St, Charlottetown, PE",
  "131 Sydney St, Charlottetown, PE",
  "150 Sydney St, Charlottetown, PE",

  // CHARLOTTETOWN - HILLSBOROUGH STREET
  "1 Hillsborough St, Charlottetown, PE",
  "10 Hillsborough St, Charlottetown, PE",
  "25 Hillsborough St, Charlottetown, PE",
  "50 Hillsborough St, Charlottetown, PE",
  "75 Hillsborough St, Charlottetown, PE",
  "100 Hillsborough St, Charlottetown, PE",

  // CHARLOTTETOWN - FITZROY STREET
  "1 Fitzroy St, Charlottetown, PE",
  "10 Fitzroy St, Charlottetown, PE",
  "25 Fitzroy St, Charlottetown, PE",
  "50 Fitzroy St, Charlottetown, PE",
  "75 Fitzroy St, Charlottetown, PE",
  "82 Fitzroy St, Charlottetown, PE",
  "100 Fitzroy St, Charlottetown, PE",

  // CHARLOTTETOWN - RESIDENTIAL NEIGHBORHOODS
  "1 Parkview Dr, Charlottetown, PE",
  "10 Parkview Dr, Charlottetown, PE",
  "25 Parkview Dr, Charlottetown, PE",
  "50 Parkview Dr, Charlottetown, PE",
  "75 Parkview Dr, Charlottetown, PE",
  "100 Parkview Dr, Charlottetown, PE",

  "1 Skyview Dr, Charlottetown, PE",
  "10 Skyview Dr, Charlottetown, PE",
  "25 Skyview Dr, Charlottetown, PE",
  "50 Skyview Dr, Charlottetown, PE",
  "75 Skyview Dr, Charlottetown, PE",

  "1 Meadowvale Dr, Charlottetown, PE",
  "10 Meadowvale Dr, Charlottetown, PE",
  "25 Meadowvale Dr, Charlottetown, PE",
  "50 Meadowvale Dr, Charlottetown, PE",
  "75 Meadowvale Dr, Charlottetown, PE",

  "1 Woodlawn Dr, Charlottetown, PE",
  "10 Woodlawn Dr, Charlottetown, PE",
  "25 Woodlawn Dr, Charlottetown, PE",
  "50 Woodlawn Dr, Charlottetown, PE",
  "75 Woodlawn Dr, Charlottetown, PE",

  "1 Highfield Dr, Charlottetown, PE",
  "10 Highfield Dr, Charlottetown, PE",
  "25 Highfield Dr, Charlottetown, PE",
  "50 Highfield Dr, Charlottetown, PE",
  "75 Highfield Dr, Charlottetown, PE",

  "1 Westwood Dr, Charlottetown, PE",
  "10 Westwood Dr, Charlottetown, PE",
  "25 Westwood Dr, Charlottetown, PE",
  "50 Westwood Dr, Charlottetown, PE",
  "75 Westwood Dr, Charlottetown, PE",

  "1 Southview Dr, Charlottetown, PE",
  "10 Southview Dr, Charlottetown, PE",
  "25 Southview Dr, Charlottetown, PE",
  "50 Southview Dr, Charlottetown, PE",
  "75 Southview Dr, Charlottetown, PE",

  "1 Norwood Rd, Charlottetown, PE",
  "10 Norwood Rd, Charlottetown, PE",
  "25 Norwood Rd, Charlottetown, PE",
  "50 Norwood Rd, Charlottetown, PE",
  "75 Norwood Rd, Charlottetown, PE",
  "100 Norwood Rd, Charlottetown, PE",

  "1 Maypoint Rd, Charlottetown, PE",
  "10 Maypoint Rd, Charlottetown, PE",
  "25 Maypoint Rd, Charlottetown, PE",
  "50 Maypoint Rd, Charlottetown, PE",
  "75 Maypoint Rd, Charlottetown, PE",
  "100 Maypoint Rd, Charlottetown, PE",

  "1 Royalty Rd, Charlottetown, PE",
  "10 Royalty Rd, Charlottetown, PE",
  "25 Royalty Rd, Charlottetown, PE",
  "50 Royalty Rd, Charlottetown, PE",
  "75 Royalty Rd, Charlottetown, PE",
  "100 Royalty Rd, Charlottetown, PE",

  // CHARLOTTETOWN - OTHER STREETS
  "1 Acadian Dr, Charlottetown, PE",
  "10 Acadian Dr, Charlottetown, PE",
  "25 Acadian Dr, Charlottetown, PE",
  "50 Acadian Dr, Charlottetown, PE",
  "  Charlottetown, PE",
  "25 Acadian Dr, Charlottetown, PE",
  "50 Acadian Dr, Charlottetown, PE",
  "75 Acadian Dr, Charlottetown, PE",
  "100 Acadian Dr, Charlottetown, PE",

  "1 Ash Dr, Charlottetown, PE",
  "10 Ash Dr, Charlottetown, PE",
  "25 Ash Dr, Charlottetown, PE",
  "50 Ash Dr, Charlottetown, PE",

  "1 Ash Ln, Charlottetown, PE",
  "10 Ash Ln, Charlottetown, PE",
  "25 Ash Ln, Charlottetown, PE",

  "1 Atlantic Dr, Charlottetown, PE",
  "10 Atlantic Dr, Charlottetown, PE",
  "25 Atlantic Dr, Charlottetown, PE",
  "50 Atlantic Dr, Charlottetown, PE",

  "1 Auburn St, Charlottetown, PE",
  "10 Auburn St, Charlottetown, PE",
  "25 Auburn St, Charlottetown, PE",

  "1 Autumn Dr, Charlottetown, PE",
  "10 Autumn Dr, Charlottetown, PE",
  "25 Autumn Dr, Charlottetown, PE",

  "1 Avonlea Dr, Charlottetown, PE",
  "10 Avonlea Dr, Charlottetown, PE",
  "25 Avonlea Dr, Charlottetown, PE",

  "1 Bayside Dr, Charlottetown, PE",
  "10 Bayside Dr, Charlottetown, PE",
  "25 Bayside Dr, Charlottetown, PE",

  "1 Beach Grove Rd, Charlottetown, PE",
  "10 Beach Grove Rd, Charlottetown, PE",
  "25 Beach Grove Rd, Charlottetown, PE",
  "50 Beach Grove Rd, Charlottetown, PE",
  "75 Beach Grove Rd, Charlottetown, PE",
  "100 Beach Grove Rd, Charlottetown, PE",

  "1 Beechwood Dr, Charlottetown, PE",
  "10 Beechwood Dr, Charlottetown, PE",
  "25 Beechwood Dr, Charlottetown, PE",

  "1 Belmont St, Charlottetown, PE",
  "10 Belmont St, Charlottetown, PE",
  "25 Belmont St, Charlottetown, PE",

  "1 Birch Hill Dr, Charlottetown, PE",
  "10 Birch Hill Dr, Charlottetown, PE",
  "25 Birch Hill Dr, Charlottetown, PE",

  "1 Brighton Rd, Charlottetown, PE",
  "10 Brighton Rd, Charlottetown, PE",
  "25 Brighton Rd, Charlottetown, PE",
  "35 Brighton Rd, Charlottetown, PE",
  "50 Brighton Rd, Charlottetown, PE",

  "1 Brows Ln, Charlottetown, PE",
  "10 Brows Ln, Charlottetown, PE",
  "25 Brows Ln, Charlottetown, PE",

  "1 Burns Ave, Charlottetown, PE",
  "10 Burns Ave, Charlottetown, PE",
  "25 Burns Ave, Charlottetown, PE",

  "1 Capital Dr, Charlottetown, PE",
  "10 Capital Dr, Charlottetown, PE",
  "25 Capital Dr, Charlottetown, PE",
  "50 Capital Dr, Charlottetown, PE",
  "75 Capital Dr, Charlottetown, PE",
  "100 Capital Dr, Charlottetown, PE",

  // SUMMERSIDE - WATER STREET
  "1 Water St, Summerside, PE",
  "10 Water St, Summerside, PE",
  "25 Water St, Summerside, PE",
  "50 Water St, Summerside, PE",
  "55 Water St, Summerside, PE",
  "75 Water St, Summerside, PE",
  "98 Water St, Summerside, PE",
  "100 Water St, Summerside, PE",
  "110 Water St, Summerside, PE",
  "125 Water St, Summerside, PE",
  "150 Water St, Summerside, PE",
  "175 Water St, Summerside, PE",
  "192 Water St, Summerside, PE",
  "200 Water St, Summerside, PE",
  "225 Water St, Summerside, PE",
  "235 Water St, Summerside, PE",
  "240 Water St, Summerside, PE",
  "250 Water St, Summerside, PE",
  "275 Water St, Summerside, PE",
  "281 Water St, Summerside, PE",
  "285 Water St, Summerside, PE",
  "300 Water St, Summerside, PE",
  "323 Water St, Summerside, PE",
  "325 Water St, Summerside, PE",
  "350 Water St, Summerside, PE",
  "375 Water St, Summerside, PE",
  "386 Water St, Summerside, PE",
  "400 Water St, Summerside, PE",
  "418 Water St, Summerside, PE",
  "425 Water St, Summerside, PE",
  "450 Water St, Summerside, PE",
  "475 Water St, Summerside, PE",
  "500 Water St, Summerside, PE",
  "525 Water St, Summerside, PE",
  "550 Water St, Summerside, PE",
  "575 Water St, Summerside, PE",
  "599 Water St, Summerside, PE",
  "600 Water St, Summerside, PE",
  "618 Water St, Summerside, PE",
  "625 Water St, Summerside, PE",
  "650 Water St, Summerside, PE",

  // SUMMERSIDE - SUMMER STREET
  "1 Summer St, Summerside, PE",
  "4 Summer St, Summerside, PE",
  "10 Summer St, Summerside, PE",
  "25 Summer St, Summerside, PE",
  "33 Summer St, Summerside, PE",
  "50 Summer St, Summerside, PE",
  "75 Summer St, Summerside, PE",
  "100 Summer St, Summerside, PE",

  // SUMMERSIDE - CENTRAL STREET
  "1 Central St, Summerside, PE",
  "6 Central St, Summerside, PE",
  "10 Central St, Summerside, PE",
  "25 Central St, Summerside, PE",
  "27 Central St, Summerside, PE",
  "50 Central St, Summerside, PE",
  "75 Central St, Summerside, PE",
  "100 Central St, Summerside, PE",

  // SUMMERSIDE - GRANVILLE STREET
  "1 Granville St, Summerside, PE",
  "25 Granville St, Summerside, PE",
  "50 Granville St, Summerside, PE",
  "75 Granville St, Summerside, PE",
  "100 Granville St, Summerside, PE",
  "125 Granville St, Summerside, PE",
  "150 Granville St, Summerside, PE",
  "175 Granville St, Summerside, PE",
  "200 Granville St, Summerside, PE",
  "225 Granville St, Summerside, PE",
  "250 Granville St, Summerside, PE",
  "275 Granville St, Summerside, PE",
  "300 Granville St, Summerside, PE",
  "325 Granville St, Summerside, PE",
  "350 Granville St, Summerside, PE",
  "375 Granville St, Summerside, PE",
  "400 Granville St, Summerside, PE",
  "425 Granville St, Summerside, PE",
  "450 Granville St, Summerside, PE",
  "454 Granville St, Summerside, PE",
  "465 Granville St, Summerside, PE",
  "475 Granville St, Summerside, PE",
  "484 Granville St, Summerside, PE",
  "500 Granville St, Summerside, PE",
  "509 Granville St, Summerside, PE",
  "511 Granville St, Summerside, PE",
  "525 Granville St, Summerside, PE",
  "530 Granville St, Summerside, PE",
  "531 Granville St, Summerside, PE",
  "535 Granville St, Summerside, PE",
  "550 Granville St, Summerside, PE",
  "555 Granville St, Summerside, PE",
  "575 Granville St, Summerside, PE",
  "600 Granville St, Summerside, PE",

  // SUMMERSIDE - POPE ROAD
  "1 Pope Rd, Summerside, PE",
  "25 Pope Rd, Summerside, PE",
  "50 Pope Rd, Summerside, PE",
  "75 Pope Rd, Summerside, PE",
  "100 Pope Rd, Summerside, PE",
  "125 Pope Rd, Summerside, PE",
  "150 Pope Rd, Summerside, PE",

  // SUMMERSIDE - RYAN STREET
  "1 Ryan St, Summerside, PE",
  "10 Ryan St, Summerside, PE",
  "25 Ryan St, Summerside, PE",
  "50 Ryan St, Summerside, PE",
  "75 Ryan St, Summerside, PE",

  // SUMMERSIDE - RESIDENTIAL NEIGHBORHOODS
  "1 Greenwood Dr, Summerside, PE",
  "10 Greenwood Dr, Summerside, PE",
  "25 Greenwood Dr, Summerside, PE",
  "50 Greenwood Dr, Summerside, PE",

  "1 Highland Ave, Summerside, PE",
  "10 Highland Ave, Summerside, PE",
  "25 Highland Ave, Summerside, PE",
  "50 Highland Ave, Summerside, PE",

  "1 Cedar St, Summerside, PE",
  "10 Cedar St, Summerside, PE",
  "25 Cedar St, Summerside, PE",
  "50 Cedar St, Summerside, PE",

  "1 Maple Ave, Summerside, PE",
  "10 Maple Ave, Summerside, PE",
  "25 Maple Ave, Summerside, PE",
  "50 Maple Ave, Summerside, PE",

  // STRATFORD
  "1 Stratford Rd, Stratford, PE",
  "10 Stratford Rd, Stratford, PE",
  "25 Stratford Rd, Stratford, PE",
  "50 Stratford Rd, Stratford, PE",
  "75 Stratford Rd, Stratford, PE",
  "100 Stratford Rd, Stratford, PE",
  "125 Stratford Rd, Stratford, PE",
  "150 Stratford Rd, Stratford, PE",
  "175 Stratford Rd, Stratford, PE",
  "200 Stratford Rd, Stratford, PE",

  "1 Glen Stewart Dr, Stratford, PE",
  "10 Glen Stewart Dr, Stratford, PE",
  "25 Glen Stewart Dr, Stratford, PE",
  "50 Glen Stewart Dr, Stratford, PE",
  "75 Glen Stewart Dr, Stratford, PE",

  "1 Keppoch Rd, Stratford, PE",
  "10 Keppoch Rd, Stratford, PE",
  "25 Keppoch Rd, Stratford, PE",
  "50 Keppoch Rd, Stratford, PE",
  "75 Keppoch Rd, Stratford, PE",

  "1 Mason Rd, Stratford, PE",
  "10 Mason Rd, Stratford, PE",
  "25 Mason Rd, Stratford, PE",
  "50 Mason Rd, Stratford, PE",
  "75 Mason Rd, Stratford, PE",

  "17 Meadowbank Rd, Stratford, PE",

  // CORNWALL
  "1 Main St, Cornwall, PE",
  "10 Main St, Cornwall, PE",
  "25 Main St, Cornwall, PE",
  "50 Main St, Cornwall, PE",
  "75 Main St, Cornwall, PE",
  "100 Main St, Cornwall, PE",

  "1 Trans-Canada Hwy, Cornwall, PE",
  "10 Trans-Canada Hwy, Cornwall, PE",
  "25 Trans-Canada Hwy, Cornwall, PE",
  "50 Trans-Canada Hwy, Cornwall, PE",
  "75 Trans-Canada Hwy, Cornwall, PE",
  "100 Trans-Canada Hwy, Cornwall, PE",

  "1 Cornwall Rd, Cornwall, PE",
  "10 Cornwall Rd, Cornwall, PE",
  "25 Cornwall Rd, Cornwall, PE",
  "50 Cornwall Rd, Cornwall, PE",
  "75 Cornwall Rd, Cornwall, PE",

  // MONTAGUE
  "1 Main St, Montague, PE",
  "10 Main St, Montague, PE",
  "25 Main St, Montague, PE",
  "50 Main St, Montague, PE",
  "75 Main St, Montague, PE",

  "1 Fraser St, Montague, PE",
  "10 Fraser St, Montague, PE",
  "25 Fraser St, Montague, PE",

  "1 Brudenell Ave, Montague, PE",
  "10 Brudenell Ave, Montague, PE",
  "25 Brudenell Ave, Montague, PE",

  "409 MacIntyre Ave, Montague, PE",
  "567 Main St, Montague, PE",
  "11 Brook St, Montague, PE",

  // KENSINGTON
  "1 Broadway St, Kensington, PE",
  "2 Broadway St N, Kensington, PE",
  "10 Broadway St, Kensington, PE",
  "25 Broadway St, Kensington, PE",

  "1 Garden Dr, Kensington, PE",
  "10 Garden Dr, Kensington, PE",
  "25 Garden Dr, Kensington, PE",

  "1 Victoria St, Kensington, PE",
  "10 Victoria St, Kensington, PE",
  "25 Victoria St, Kensington, PE",

  // SOURIS
  "1 Main St, Souris, PE",
  "10 Main St, Souris, PE",
  "25 Main St, Souris, PE",

  "1 Church St, Souris, PE",
  "10 Church St, Souris, PE",
  "25 Church St, Souris, PE",

  "17 Knights Ave, Souris, PE",
  "336 Basin Head Rd, Souris, PE",

  // ALBERTON
  "148 Poplar St, Alberton, PE",
  "169 Peninsula Rd, Alberton, PE",

  // TIGNISH
  "1 Main St, Tignish, PE",
  "10 Main St, Tignish, PE",
  "25 Main St, Tignish, PE",

  // GEORGETOWN
  "1 Main St, Georgetown, PE",
  "10 Main St, Georgetown, PE",
  "25 Main St, Georgetown, PE",

  "86 Dewars Ln, Georgetown, PE",
  "82 Greenwich Rd, Montague, PE",

  // BORDEN-CARLETON
  "3 Stan MacPherson Way, Borden-Carleton, PE",
  "100 Abegweit Blvd, Borden-Carleton, PE",
  "103 Abegweit Blvd, Borden-Carleton, PE",

  // CAVENDISH
  "8619 Cavendish Rd, Cavendish, PE",
  "591 Graham's Ln, Cavendish, PE",
  "8779 Route 6, Cavendish, PE",
  "7591 Cawnpore Ln, Cavendish, PE",
  "8521 Cavendish Rd, Cavendish, PE",

  // NORTH RUSTICO
  "312 Harbourview Dr, North Rustico, PE",
  "7230 Rustico Rd, North Rustico, PE",

  // TRANSPORTATION HUBS
  "Charlottetown Airport (YYG), 250 Maple Hills Ave, Charlottetown, PE",
  "Summerside Airport, 30 Leo Handrahan Dr, Summerside, PE",
  "Confederation Bridge, Trans-Canada Hwy, Borden-Carleton, PE",
  "Wood Islands Ferry Terminal, 13910 Trans-Canada Hwy, Wood Islands, PE",

  // HOTELS AND ACCOMMODATIONS
  "Delta Hotels by Marriott Prince Edward, 18 Queen St, Charlottetown, PE",
  "The Great George Hotel, 58 Great George St, Charlottetown, PE",
  "Rodd Charlottetown, 75 Kent St, Charlottetown, PE",
  "Holman Grand Hotel, 123 Grafton St, Charlottetown, PE",
  "Rodd Crowbush Golf & Beach Resort, 632 Route 350, Morell, PE",
  "Rodd Brudenell River Resort, 86 Dewars Ln, Georgetown, PE",
  "Dalvay by the Sea, 16 Dalvay Beach Rd, York, PE",
  "Inn at St. Peters, 1668 Greenwich Rd, St. Peters Bay, PE",
  "Quality Inn & Suites, 618 Water St E, Summerside, PE",
  "Loyalist Country Inn, 195 Heather Moyse Dr, Summerside, PE",

  // TOURIST ATTRACTIONS
  "Green Gables Heritage Place, 8619 Cavendish Rd, Cavendish, PE",
  "Cavendish Beach, 591 Graham's Ln, Cavendish, PE",
  "Prince Edward Island National Park, 7 Cawnpore Ln, Charlottetown, PE",
  "Confederation Centre of the Arts, 145 Richmond St, Charlottetown, PE",
  "Province House National Historic Site, 165 Richmond St, Charlottetown, PE",
  "Avonlea Village, 8779 Route 6, Cavendish, PE",
  "Basin Head Provincial Park, 336 Basin Head Rd, Souris, PE",
  "Point Prim Lighthouse, 2147 Point Prim Rd, Belfast, PE",
  "Victoria Park, 35 Brighton Rd, Charlottetown, PE",
  "Brackley Beach, 4021 Brackley Point Rd, Brackley Beach, PE",
  "Greenwich Beach, 59 Wild Rose Rd, St. Peters Bay, PE",

  // SHOPPING AND COMMERCIAL AREAS
  "Charlottetown Mall, 670 University Ave, Charlottetown, PE",
  "Confederation Court Mall, 134 Kent St, Charlottetown, PE",
  "County Fair Mall, 475 Granville St N, Summerside, PE",
  "Downtown Charlottetown, Queen St, Charlottetown, PE",
  "Peakes Quay, 6 Prince St, Charlottetown, PE",

  // HEALTHCARE FACILITIES
  "Queen Elizabeth Hospital, 60 Riverside Dr, Charlottetown, PE",
  "Prince County Hospital, 65 Roy Boates Ave, Summerside, PE",
  "Kings County Memorial Hospital, 409 MacIntyre Ave, Montague, PE",
  "Western Hospital, 148 Poplar St, Alberton, PE",
  "Souris Hospital, 17 Knights Ave, Souris, PE",

  // EDUCATIONAL INSTITUTIONS
  "University of Prince Edward Island, 550 University Ave, Charlottetown, PE",
  "Holland College, 140 Weymouth St, Charlottetown, PE",
  "Maritime Christian College, 503 University Ave, Charlottetown, PE",
  "Atlantic Veterinary College, 550 University Ave, Charlottetown, PE",
  "Colonel Gray High School, 175 Spring Park Rd, Charlottetown, PE",
  "Charlottetown Rural High School, 100 Raiders Rd, Charlottetown, PE",
  "Three Oaks Senior High School, 10 Kenwood Dr, Summerside, PE",

  // RESTAURANTS AND BUSINESSES
  "Fishbones Oyster Bar & Grill, 136 Richmond St, Charlottetown, PE",
  "Hunters Ale House, 185 Kent St, Charlottetown, PE",
  "Gahan House, 126 Sydney St, Charlottetown, PE",
  "Merchantman Fresh Seafood & Oyster Bar, 23 Queen St, Charlottetown, PE",
  "Peakes Quay Restaurant & Bar, 6 Prince St, Charlottetown, PE",
  "Claddagh Oyster House, 131 Sydney St, Charlottetown, PE",
  "Lobster on the Wharf, 2 Prince St, Charlottetown, PE",
  "Water Prince Corner Shop, 141 Water St, Charlottetown, PE",
  "Cows Creamery, 12 Milky Way, Charlottetown, PE",
  "Receiver Coffee Co., 128 Richmond St, Charlottetown, PE",
  "Upstreet Craft Brewing, 41 Allen St, Charlottetown, PE",
  "PEI Brewing Company, 96 Kensington Rd, Charlottetown, PE",
  "Sobeys, 65 Grafton St, Charlottetown, PE",
  "Atlantic Superstore, 465 University Ave, Charlottetown, PE",
  "Walmart Supercentre, 80 Buchanan Dr, Charlottetown, PE",
  "Canadian Tire, 40 Buchanan Dr, Charlottetown, PE",
  "Charlottetown Farmers Market, 100 Belvedere Ave, Charlottetown, PE",
  "Brothers 2 Restaurant, 618 Water St E, Summerside, PE",
  "Chez Yvonne's Restaurant, 323 Water St, Summerside, PE",
  "South Central Kitchen & Provisions, 98 Water St, Summerside, PE",
  "Evermoore Brewing Company, 192 Water St, Summerside, PE",
  "Samuel's Coffee House, 4 Queen St, Summerside, PE",
  "Atlantic Superstore, 535 Granville St N, Summerside, PE",
  "Sobeys, 475 Granville St N, Summerside, PE",
  "Walmart Supercentre, 511 Granville St N, Summerside, PE",

  // GOVERNMENT BUILDINGS
  "Charlottetown City Hall, 199 Queen St, Charlottetown, PE",
  "Service Canada Centre, 191 Great George St, Charlottetown, PE",
  "Access PEI Charlottetown, 33 Riverside Dr, Charlottetown, PE",
  "Summerside City Hall, 275 Fitzroy St, Summerside, PE",
  "Access PEI Summerside, 120 Heather Moyse Dr, Summerside, PE",

  // PARKS AND RECREATION
  "Victoria Park, 35 Brighton Rd, Charlottetown, PE",
  "Confederation Landing Park, 38 Water St, Charlottetown, PE",
  "Ardgowan National Historic Site, 2 Palmers Ln, Charlottetown, PE",
  "Rotary Friendship Park, 315 North River Rd, Charlottetown, PE",
  "Tea Hill Provincial Park, 17 Meadowbank Rd, Stratford, PE",
  "Heather Moyse Heritage Park, 130 Water St, Summerside, PE",
  "Green's Shore Beach, 55 Harbour Dr, Summerside, PE",

  // COMMON INTERSECTIONS
  "University Ave & Belvedere Ave, Charlottetown, PE",
  "Queen St & Grafton St, Charlottetown, PE",
  "Queen St & Kent St, Charlottetown, PE",
  "University Ave & Allen St, Charlottetown, PE",
  "North River Rd & Capital Dr, Charlottetown, PE",
  "St. Peters Rd & Riverside Dr, Charlottetown, PE",
  "Water St & Queen St, Charlottetown, PE",
  "Water St & Summer St, Summerside, PE",
  "Water St & Central St, Summerside, PE",
  "Pope Rd & Roy Boates Ave, Summerside, PE",
]

